CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE SALA(
ID_SALA BIGINT NOT NULL AUTO_INCREMENT,
CAPACIDADE INT(3) NOT NULL,
ANDAR  INT (2) NOT NULL,
PRIMARY KEY (ID_SALA)
)
ENGINE = INNODB;

CREATE TABLE ALUNO(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (256),
EMAIL VARCHAR (256),
TELEFONE VARCHAR (256),
ALTURA DECIMAL (3,2),
PRIMARY KEY (ID)
)
ENGINE INNODB;

INSERT INTO SALA (CAPACIDADE, ANDAR) VALUES (40, 1);
INSERT INTO SALA (CAPACIDADE, ANDAR) VALUES (35, 1);
INSERT INTO SALA (CAPACIDADE, ANDAR) VALUES (38, 2);
INSERT INTO ALUNO (NOME, EMAIL, TELEFONE, ALTURA) VALUES ('JONAS MAIA', 'MAIA@NOSSODOMINIO.COM.BR', '12345678', 1.76);
INSERT INTO ALUNO (NOME, EMAIL, TELEFONE, ALTURA) VALUES ('RAFAEL COSENTINO', 'COSENTINO@NOSSODOMINIO.COM.BR', 22222222, 1.57);

SELECT * FROM SALA;
SELECT * FROM ALUNO;

UPDATE ALUNO
SET NOME = 'JOÃO'
WHERE ID = 1;

UPDATE SALA
SET ANDAR = 2
WHERE ID = 1;

DELETE FROM ALUNO
WHERE ID = 2;