DROP SCHEMA IF EXISTS FICHAMEDICA;
CREATE SCHEMA FICHAMEDICA;
USE FICHAMEDICA;

CREATE TABLE ADDRESS(
ADDRESS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FEDERAL_STATE VARCHAR(255) NOT NULL,
CITY VARCHAR(255) NOT NULL,
STREET VARCHAR(255) NOT NULL,
HOUSE_NUMBER VARCHAR(10) NOT NULL
);

CREATE TABLE PERSON(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FULL_NAME VARCHAR(100) NOT NULL,
BIRTH_DATE DATE NOT NULL,
SEX VARCHAR (20) NOT NULL,
CPF VARCHAR(20) NOT NULL UNIQUE,
RG VARCHAR(20) NOT NULL UNIQUE,
PHONE VARCHAR(20) NOT NULL,
CIVIL_STATUS VARCHAR(20) NOT NULL,
ADDRESS_ID INT NOT NULL,
CONSTRAINT FK_PERSON_ADDRESS
	FOREIGN KEY(ADDRESS_ID)
	REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE DOCTOR(
DOCTOR_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PERSON_ID INT NOT NULL,
CONSTRAINT FK_DOCTOR_PERSON
	FOREIGN KEY(PERSON_ID)
    REFERENCES PERSON(ID)
);

CREATE TABLE PATIENT(
PATIENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PERSON_ID INT NOT NULL,
CONSTRAINT FK_PATIENT_PERSON
	FOREIGN KEY (PERSON_ID)
    REFERENCES PERSON(ID)
);

CREATE TABLE CONSULTATION(
CONSULTATION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`DATE` DATETIME NOT NULL,
DOCTOR_ID INT NOT NULL,
DIAGNOSIS VARCHAR(255) NOT NULL,
PATIENT_ID INT NOT NULL,
CONSTRAINT FK_CONSULTATION_DOCTOR
	FOREIGN KEY(DOCTOR_ID)
    REFERENCES DOCTOR(DOCTOR_ID),
CONSTRAINT FK_CONSULTATION_PATIENT
	FOREIGN KEY(PATIENT_ID)
    REFERENCES PATIENT(PATIENT_ID)
);


