CREATE DATABASE INSCRICOES;

USE `INSCRICOES`; 

CREATE TABLE `PESSOAS`(
`ID_PESSOA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NOME_PESSOA` VARCHAR(256) NOT NULL,
`EMAIL` VARCHAR(256) NOT NULL
);

CREATE TABLE `MINICURSOS`(
`ID_MINICURSO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`DATA_INICIO` DATETIME NOT NULL,
`DATA_FIM` DATETIME NOT NULL
);

CREATE TABLE `PALESTRAS`(
`ID_PALESTRA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`HORA_INICIO` DATETIME NOT NULL,
`HORA_FIM` DATETIME NOT NULL
);

CREATE TABLE `INSCRICOES_MINICURSOS`(
`ID_INSCRICAO_MINICURSO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`ID_PESSOA` INT NOT NULL,
`ID_MINICURSO` INT NOT NULL,
`DATA` DATETIME NOT NULL
);

CREATE TABLE `INSCRICOES_PALESTRAS`(
`ID_INSCRICAO_PALESTRA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`ID_PESSOA` INT NOT NULL,
`ID_PALESTRA` INT NOT NULL,
`DATA` DATETIME NOT NULL
);