CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE EDITORA(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (256) NOT NULL,
EMAIL VARCHAR (256) NOT NULL,
ANO_NASCIMENTO INT NOT NULL,
NACIONAL BOOL NOT NULL,
PRIMARY KEY (ID)
)
ENGINE INNODB;

INSERT INTO EDITORA (NOME, EMAIL, ANO_NASCIMENTO, NACIONAL) VALUES ('EDITORA1', 'EDITORA1@EMAIL.COM', 1998, 0);
INSERT INTO EDITORA (NOME, EMAIL, ANO_NASCIMENTO, NACIONAL) VALUES ('EDITORA2', 'EDITORA2@EMAIL.COM', 2003, 1);

SELECT * FROM EDITORA;

UPDATE EDITORA
SET ANO_NASCIMENTO = 1999
WHERE ID = 1;

DELETE FROM EDITORA
WHERE ID = 2;