DROP SCHEMA IF EXISTS nota_fiscal_normalizada;
CREATE DATABASE NOTA_FISCAL_NORMALIZADA;

USE `NOTA_FISCAL_NORMALIZADA`;

CREATE TABLE `NOTA_FISCAL`(
`NRO_NOTA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NM_CLIENTE` VARCHAR(256) NOT NULL,
`END_CLIENTE` VARCHAR(256) NOT NULL,
`NM_VENDEDOR` VARCHAR(256) NOT NULL,
`DT_EMISSAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
`VL_TOTAL` FLOAT NOT NULL
);

CREATE TABLE `PRODUTO`(
`COD_PRODUTO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`DESC_PRODUTO` VARCHAR(256) NOT NULL,
`UN_MED` CHAR(2) NOT NULL,
`VL_PRODUTO` FLOAT NOT NULL 
);

CREATE TABLE `ITEM_NOTA_FISCAL`(
`NRO_NOTA` INT NOT NULL,
`COD_PRODUTO` INT NOT NULL,
`QTD_PRODUTO` INT NOT NULL,
`VL_PRECO` FLOAT NOT NULL,
`VL_TOTAL` FLOAT NOT NULL,
PRIMARY KEY(NRO_NOTA, COD_PRODUTO),
CONSTRAINT FK_NRO_NOTA_FISCAL
	FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL (NRO_NOTA),
CONSTRAINT FK_COD_PRODUTO_PRODUTO
	FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
);

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('Leite', 'LT', 4.50);

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('Desodorante', 'UN', 8.00);

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('Salame', 'KG', 100.00);

SELECT * FROM `PRODUTO`;

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('Aragon', 'Terra Média', 'Bilso', 100.00);

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('Gandalf', 'Terra Média', 'Frodo', 100.00);

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('Boromir', 'Mordor', 'Sam', 100.00);

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('Galadriel', 'Valinor', 'Saruman', 100.00);

SELECT * FROM `NOTA_FISCAL`;

-- Item da Nota

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (1, 1, 1, 4.50, 4.50);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (1, 2, 2, 40.00, 80.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (1, 3, 10, 100.00, 1000.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (2, 1, 1, 100.00, 100.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (2, 2, 1, 40.00, 40.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (2, 3, 2, 100.00, 200.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (3, 1, 10, 100.00, 1000.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (3, 2, 10, 100.00, 1000.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (3, 3, 10, 100.00, 1000.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (4, 1, 1, 4.50, 4.50);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (4, 2, 2, 40.00, 80.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (4, 3, 3, 100.00, 300.00);

SELECT * FROM ITEM_NOTA_FISCAL;

SELECT * FROM PRODUTO WHERE COD_PRODUTO = 3;

-- Update atualizando dados de colunas em tabelas 
UPDATE PRODUTO
SET VL_PRODUTO = 45, DESC_PRODUTO = 'Atualizado',
UN_MED = 'CX'
WHERE COD_PRODUTO = 3;

-- Delete, excluindo registros de tabelas
DELETE FROM PRODUTO
WHERE COD_PRODUTO = '3';
-- Neste caso uma exceção será lançada
-- Violação de constraint que amarra o produto ao
-- item da nota fiscal, não é possível excluir uma
-- PK que tem dependência em FKs

INSERT INTO PRODUTO (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('Teste Delete', 'LT', 5.50);

SELECT * FROM PRODUTO;
